pip install keyboard
pip install tkinter.simpledialog
pip install sys
pip install csv
pip install wavefile
pip install tkinter
pip install json
pip install numpy
pip install wave
pip install pyaudio
pip install shutil
pip install os
pip install re
pip install soundfile
pip install psutil
pip install subprocess
pip install cssutils
pip install argparse
